version: '3'
services:

    cove:
        build:
            context: cove
        image: openagdata/cove
        container_name: openag_cove
        ports:
            - 8000:8000

    nerserver:
        build:
            context: nerserver
        image: openagdata/nerserver
        container_name: openag_nerserver
        ports:
            - 9000:9000

    geocoder:
        build:
            context: geocoder
        image: openagdata/geocoder
        container_name: openag_geocoder
        environment:
            OPENAG_NERSERVER: nerserver
        links:
            - nerserver
        depends_on:
            - nerserver
        ports:
            - 5000:5000

    dportal:
        build:
            context: dportal
        image: openagdata/dportal
        container_name: openag_dportal
        ports:
            - 8011:8011

    toolbox:
        build:
            context: toolbox
        image: openagdata/geocoder
        container_name: openag_toolbox
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080

