<?php

namespace OagBundle\Repository;

/**
 * OagFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OagFileRepository extends \Doctrine\ORM\EntityRepository
{
}
